### ISSUE TITLE
Export not working with Sketch 52.x

### ISSUE THREAD

**Issue by ggolcher** [tudou527/marketch#180] opened 2018-10-09 14:23 UTC
Sketch version: 52 (all versions)

I click on export, and it starts but never produces the output files. It still works great in version 51.x, but 52.x is broken.

**Comment by craigleadspark** [comment] 2018-10-10 09:19
I am currently experiencing the same issue on 52.1. Please could someone let me know if there is a work around for this. 

Unfortunately downloading a previous version of Sketch doesn't pull in the design file correctly, so not an option this time.

**Comment by MForever78** [comment] 2018-10-11 17:56
This is caused by Sketch API change. Marketch used to rely on `layer.style().sharedStyleID()` to get the shared style (that's the shape or text in the right panel).

I may consider removing this temporarily to workaround this.

**Comment by MForever78** [comment] 2018-10-11 18:00
fixed in 49ebd0c9 .

Please help verify and let me know if there's still issues.

**Comment by ggolcher** [comment] 2018-10-11 18:14
The Marketch version checker says a new version is available, but Sketchpacks does not offer it to me

**Comment by MForever78** [comment] 2018-10-11 18:17
I'm not sure how Sketchpacks works. Can you install the new version here? Download the zip, uncompress and double click `marketch.sketchplugin`

https://github.com/tudou527/marketch/releases

**Comment by ggolcher** [comment] 2018-10-11 18:32
It's working! I can now use Sketch 52 for my work. Thank you very much! :D

**Comment by MForever78** [comment] 2018-10-11 18:32
Cool. Thanks for verifying.

Closing.

**Closed by MForever78** 2018-10-11 18:32 UTC
