### ISSUE TITLE
Won't Export Zip Files.

### ISSUE THREAD

**Issue by jolieangeline** [tudou527/marketch#149] opened 2017-07-25 16:20 UTC
# Issue template

Today I tried to make a Zip archive of my work, but nothing appeared in the chosen folder. It just writes "Exporting..." on the Page screen, then flashes white, and nothing happens! HELP!

Sketch version - 45.2,
Marketch version - 1.0.22

**Comment by tamcao** [comment] 2017-07-28 14:28
Same Issue here. Also using sketch v 45.2 .  Has anyone figure out how to make this work?  This is a really great plugin! Please Help.

**Comment by igalanga** [comment] 2017-07-31 01:30
Same happen to me mate. 

I can't export it into HTML... 

it says exporting but when i check the file, nothing is showing up! 

Same problem as the old one. Anyone can help me with this? 

Thank you guys~

**Comment by vivachu** [comment] 2017-08-01 21:02
Same here!  Please help!

**Comment by raulgrafico** [comment] 2017-08-01 21:03
I have the same issue, please guys fix it.

**Comment by kpmoran** [comment] 2017-08-01 22:54
So while I haven't solved this I believe that I have found a workaround. I was able to isolate the problem to line 425 in marketch/marketch.sketchplugin/Contents/Sketch/util.cocoascript . Basically, it seems the issue is related to having Text Objects that have "Fills" in them.  If I remove any "Fills" from these text objects, marketch seems to export without an issue. Hope this helps some having this issue.

**Comment by tamcao** [comment] 2017-08-01 23:16
The workaround works perfectly.  Thanks @kpmoran!

**Comment by hahnzhu** [comment] 2017-08-03 07:58
@kpmoran works for me too! remove the fill effect from text (移除文字里的填充效果)

**Comment by igalanga** [comment] 2017-08-03 08:04
Works great mate.

Commenyed the code


--
Ignacio Galanga Jr.

On Aug 3, 2017 3:58 PM, "Hahn" <notifications@github.com> wrote:

@kpmoran <https://github.com/kpmoran> works for me too! remove the fill
effect from text (移除文字里的填充效果)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tudou527/marketch/issues/149#issuecomment-319897347>,
or mute the thread

**Comment by AbnerChen028** [comment] 2017-08-08 06:38
Thanks   @kpmoran !

**Comment by brianlzw** [comment] 2017-09-19 23:18
Thanks @kpmoran!
Removing the "filled" color from text works!

Hope this bug will be addressed soon.

**Comment by MForever78** [comment] 2017-11-18 13:02
Fixed in 6f4e2a6.

Please upgrade to 1.0.23.

**Closed by MForever78** 2017-11-18 13:02 UTC
